site_name: SHEET / MOS-Bench
repo_url: https://github.com/unilight/sheet
site_url: https://unilight.github.io/sheet
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  favicon: https://raw.githubusercontent.com/unilight/sheet/refs/heads/main/assets/sheet-favicon.png
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
#  - git-revision-date-localized
  - social:
      cards_layout_options:
        title: SHEET / MOS-Bench
        description: Documentation website of the SHEET toolkit and the MOS-Bench dataset collection.
nav:
  - Home: index.md
  - MOS-Bench: mos-bench.md
  - Training guide: training.md
  - Benchmarking guide: benchmarking.md
  - List of pre-trained models: pretrained-models.md
