site_name: SHEET / MOS-Bench
repo_url: https://github.com/unilight/sheet
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  favicon: https://raw.githubusercontent.com/unilight/sheet/refs/heads/main/assets/sheet-favicon.png
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
nav:
  - Home: index.md
  - MOS-Bench: mos-bench.md
  - Training guide: training.md
  - Benchmarking guide: benchmarking.md