###########################################################
#                  FINE-TUNING SETTING                    #
###########################################################
init-mods: ["ssl_model", "mean_net_dnn"]
freeze-mods: null

###########################################################
#                      LOSS SETTING                       #
###########################################################
mean_score_criterions:
    - criterion_type: "ScalarLoss"
      criterion_weight: 1.0
      criterion_params:
        order: 1
        tau: 0.5
        masked_loss: False
listener_score_criterions: null

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
dev_samples_per_eval_loop: 1000
allow_cache: false           # Whether to allow cache in dataset. If true, it requires cpu memory.

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################
optimizer_type: SGD
optimizer_params:
    lr: 1.0e-3
    # the following params come from
    # https://github.com/pytorch/vision/blob/c2ab0c59f42babf9ad01aa616cd8a901daac86dd/references/classification/train.py#L172-L173
    momentum: 0.9
grad_norm: 1.0              # Gradient norm.
scheduler_type: null

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 100000                 # Number of training steps.
eval_and_save_interval_steps: 1000      # Interval steps to do evaluation and save checkpoint.
log_interval_steps: 100                 # Interval steps to record the training log.
keep_nbest_models: 5                    # number of models to keep
patience: 20                            # patience for early stopping
best_model_criterion:                   # criterion to save the best models
    key: utt_SRCC
    order: highest                      # choices: lowest, highest